# Generated by Django 6.0.3 on 2026-03-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='role',
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
