# Generated by Django 6.0.3 on 2026-04-21 17:07

from datetime import time

from django.db import migrations, models


def seed_operating_hours(apps, schema_editor):
    OperatingHours = apps.get_model("scheduling", "OperatingHours")
    defaults = [
        (0, time(11, 0), time(22, 0)),
        (1, time(11, 0), time(22, 0)),
        (2, time(11, 0), time(22, 0)),
        (3, time(11, 0), time(22, 0)),
        (4, time(11, 0), time(23, 0)),
        (5, time(10, 0), time(23, 0)),
        (6, time(10, 0), time(21, 0)),
    ]
    for day_of_week, open_time, close_time in defaults:
        OperatingHours.objects.get_or_create(
            day_of_week=day_of_week,
            defaults={
                "open_time": open_time,
                "close_time": close_time,
                "is_closed": False,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_assignment_options_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day_of_week'],
            },
        ),
        migrations.RunPython(seed_operating_hours, migrations.RunPython.noop),
    ]
