# Generated by Django 6.0.3 on 2026-05-18 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_staffingrequirement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baselineavailability',
            options={'ordering': ['employee__name', 'day_of_week']},
        ),
        migrations.AlterField(
            model_name='baselineavailability',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='baselineavailability',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
