# Generated by Django 6.0.3 on 2026-05-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_alter_baselineavailability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffingrequirement',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
