# Generated by Django 6.0.3 on 2026-05-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_dashboard_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
