# Generated by Django 6.0.3 on 2026-05-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_add_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='employees_with_role', to='scheduling.role'),
        ),
    ]
