# Generated by Django 6.0.3 on 2026-05-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0019_scheduleweek_published_shifts_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='slots_override',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
